# Generated by Django 3.0 on 2021-04-22 19:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='N/A', max_length=500)),
                ('text', models.CharField(default='N/A', max_length=255)),
                ('occupation', models.CharField(default='N/A', max_length=255)),
                ('industry', models.CharField(default='N/A', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('location', models.CharField(default='N/A', max_length=255)),
                ('salary', models.IntegerField(default=0)),
                ('paycheck', models.IntegerField(default=0)),
                ('debt', models.IntegerField(default=0)),
                ('net_worth', models.IntegerField(default=0)),
                ('rent', models.IntegerField(default=0)),
                ('pronouns', models.CharField(blank=True, max_length=255)),
                ('gender', models.CharField(blank=True, max_length=255)),
                ('other_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': True,
            },
        ),
    ]
